# fly.toml app configuration file generated for full-stack-open-pokedex-falling-leaf-3940 on 2024-12-05T08:17:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "full-stack-open-pokedex-falling-leaf-3940"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
    success_status = 200
    failure_threshold = 2

[deploy]
  strategy = "canary"
  