# fly.toml app configuration file generated for full-stack-open-pokedex-falling-leaf-3940 on 2024-12-05T08:17:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file

app = 'full-stack-open-pokedex-falling-leaf-3940'
primary_region = 'arn'

[build]

[env]
  PORT = "3000" # ensure PORT matches internal_port below

[processes]
  app = "node app.js" # define the process to run your app

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # link the service to the app process

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
    success_status = 200
    failure_threshold = 2

[deploy]
  strategy = "canary"
