name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint -- --fix

      - name: Run Jest tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV

      - name: Deploy App
        if: ${{ github.event_name == 'push' && env.CONDITION != 'true' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Debug Webhook
        run: echo ${{ secrets.DISCORD_WEBHOOK_URL }}
        
      - name: Notify Success to Discord
        if: ${{ success() }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "embeds": [
                  {
                    "content": "Build deployed"
                    "title": "A new version of Pokedex deployed",
                    "url": "https://pdex.fly.dev/",
                    "description": "Deployed by '${{ github.actor }}'",
                    "color": 3066993,
                    "footer": {
                      "text": "Severity: Informational"
                    }
                  }
                ]
              }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
        
      - name: Notify Failure to Discord
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "embeds": [
                  {
                    "content": "Build or Deployment Failed"
                    "title": "Build or Deployment Failed",
                    "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
                    "description": "Commit by '${{ github.actor }}' caused the failure. [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                    "color": 15158332,
                    "footer": { "text": "Severity: Error" }
                  }
                ]
              }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"